rot_cipher.lo: /home/user/rot_cipher/rot_cipher.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/home/user/rot_cipher $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /home/user/rot_cipher/rot_cipher.c -o rot_cipher.lo 
$(phplibdir)/rot_cipher.la: ./rot_cipher.la
	$(LIBTOOL) --mode=install cp ./rot_cipher.la $(phplibdir)

./rot_cipher.la: $(shared_objects_rot_cipher) $(ROT_CIPHER_SHARED_DEPENDENCIES)
	$(LIBTOOL) --mode=link $(CC) $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS) $(LDFLAGS)  -o $@ -export-dynamic -avoid-version -prefer-pic -module -rpath $(phplibdir) $(EXTRA_LDFLAGS) $(shared_objects_rot_cipher) $(ROT_CIPHER_SHARED_LIBADD)

